config:
   ci: 'BITRISE'
   url: http://codestats.wolox.com.ar/
   token: <%= ENV['CODE_STATS_TOKEN'] %>
metrics:
   slather:
     enabled: true
     minimum: 85
     upload_report: true
   swiftlint:
     enabled: true
     minimum: 90
     upload_report: false
