xcodeproj: ./WolmoReactiveCore.xcodeproj
scheme: WolmoReactiveCore
ignore:
  # AV objects can't be tested.
  - WolmoReactiveCore/Extensions/AVFoundation/*
  # Tests
  - WolmoReactiveCoreTests/*
  # Dependencies
  - Carthage/*
